export const API_URL = process.env.NODE_ENV === "test" ? "http://mocked-api-url" : import.meta.env.VITE_API_URL;
export const REGISTER = import.meta.env.VITE_REGISTER;
export const LOGIN = import.meta.env.VITE_LOGIN;
export const LOGGED_IN = import.meta.env.VITE_LOGGED_IN;
export const LOGOUT = import.meta.env.VITE_LOGOUT;
export const OFFERS = import.meta.env.VITE_OFFERS;
export const EVENTS = import.meta.env.VITE_EVENTS;
export const NOTES = import.meta.env.VITE_NOTES;
export const GUESTS = import.meta.env.VITE_GUESTS;
export const TASK_MONTHS = import.meta.env.VITE_TASK_MONTHS;